### ISSUE TITLE
Cannot get nodes to show on palette

### ISSUE THREAD

**Issue by NSEchris** [alisdairjsmyth/node-red-contrib-lifx-api#1]
I'm new at node, npm, node-red, etc.  I tried installing node-red-contrib-lifx-api on these versions, and have not been successful getting the nodes to show up on the palette:
- beaglebone running: node-red v0.15.2, Node.js v0.12.18, NPM v2.15.11
- Ubuntu 16.04 running: node-red XX, Node.js v4.2.6, NPM 3.5.2
- Bitanami VM preloaded with node-red v0.16.2, Node.js v7.4.0, NPM v4.0.5

I tried the various versions because I read there were issues with certain versions of these packages, and hoped I'd get lucky and happen to find a combo that works.   

The console shows a warning message when starting node-red of "[lifx-api] Error: Cannot find module 'lifx-http-api'"

This could be as simple as I don't know the proper procedure to install the nodejs dependency, but I don't know.  I would really appreciate any help you could offer.

PS - I do have a different lifx node working, but it doesn't provide a way to use the effects.

**Comment by alisdairjsmyth** [comment]
I just did a clean install on a RPI and experienced the same issue.  One thing that looked odd was the structure of `~/.node-red/node_modules` - rather than being a tree of dependencies, it was flat.  I will need to investigate further.

**Comment by alisdairjsmyth** [comment]
If I install this package using npm@2 (`sudo npm install -g npm@2.x`) I get the tree structure expected and the lifx nodes appear in the node-red palette.  (macOS, node-red 0.15.1, Node.js 6.6.0, npm 2.15.11)
I am away from RPI right now, so I can't confirm whether using npm@2 fixes what I observed earlier.  I will try when I get a chance.

**Comment by alisdairjsmyth** [comment]
Issue appears to have been introduced in v1.0.2 of [lifx-http-api](https://www.npmjs.com/package/lifx-http-api).  The [package.json](https://github.com/klarstil/lifx-http-api/commit/fb476c682da02e10c2321a8d4494d6aed601f37f) on github includes the following change:
```
-  "main": "source/lifx.js",
+  "main": "dist/lifx.js",
```
... however the image of the package.json included in npm install (1.0.2) is not reflective of this change and still points to ```source/lifx.js``` which does not exist.  Have raised an issue on that project.

**Comment by alisdairjsmyth** [comment]
npm version 1.0.1 includes a temporary fix for this issue.

**Comment by NSEchris** [comment]
Thanks for jumping on this right away and working out the solution!  I can
confirm that installing 1.0.1 did resolve the node-red launch error, and
the nodes are available on the palette.  I didn't have time to test it's
functionality, but I will do that tonight.  Thanks again, I really
appreciate that you created this node!
