### ISSUE TITLE
Cant use variables 

### ISSUE THREAD

**Issue by everything-tech-related** [alisdairjsmyth/node-red-contrib-lifx-api#12]
Maybe I'm not using the correct format. I can set power to "on or off" however I cant  pass a variable with the intended power state. msg.payload doesn't work.

**Comment by alisdairjsmyth** [comment]
It is working fine for me.  I tested it using the following flow:

![image](https://user-images.githubusercontent.com/11627564/60780394-9d189d80-a181-11e9-9e19-c10c64d62aab.png)

The function node includes the following:
```
msg.payload = {
    "selector": "label:Hall Near Door",
    "power": "on"
}
return msg;
```

If you still can't get it to work, attach a copy of your `msg.payload` and I will have a look.

**Comment by everything-tech-related** [comment]
So do you have to manually type "on" in Power section?

**Comment by alisdairjsmyth** [comment]
All these nodes support static and dynamic behaviour.  If you want a node to perform a specific operation on a defined set of globes (eg a node to turn on the power of a specific globe), you can use the Node-Red editor.  In this setup, the `msg.payload` is just the trigger and need not contain any value.
However if you have logic in your flow to dynamically set values, you can use `msg.payload` to send these values to the node.

> So do you have to manually type "on" in Power section?

I am interpreting this to mean in the Node-Red editor, and so would be a static definition.  The power section supports the values **on** and **off**.
![image](https://user-images.githubusercontent.com/11627564/60785159-369d7a80-a195-11e9-8d2b-9ceec387be8e.png)

**Comment by everything-tech-related** [comment]
:) I'm a bit confused with what you just said. Can you make your reply a bit simpler?

Let me try to explain better. I'm sending a voice command to alexa, "turn on bedroom light"

I can see the mag.payloay "on"
 But how do I get "on" string to paste inside the Power text input? 
I tried msg.payload...payLoad...nothing works.

I want to use one state node to turn light on or off. 

Forgive me if your above answer is correct. I just don't understand it.

**Comment by everything-tech-related** [comment]
- 
![Screenshot_20190707-224700_Chrome](https://user-images.githubusercontent.com/51037594/60785908-7a4aa280-a109-11e9-8368-85621d90f2a0.jpg)

**Comment by alisdairjsmyth** [comment]
Given you want to use one state node to turn a globe on and off, you need to use `msg.payload`.  To turn it on, you would need to inject a:
```
msg.payload = {
    "selector": "label:Deveraux",
    "power": "on"
}
```
and off:
```
msg.payload = {
    "selector": "label:Deveraux",
    "power": "off"
}
```
You may need to use a Function node to set `msg.payload`.

That said, if you want to use Alexa to control your globes there is native support available (see "[LIFX Help Center](https://support.lifx.com/hc/en-us/articles/206097366-Amazon-Echo-Alexa-)").

**Comment by everything-tech-related** [comment]
Hi I was able to make it work with a switch node. But I also want to be able to change colors without creating seperate nodes. I have native alexa support for lifx. But I want to use node red to tie everything into a single dashboard. More projects to follow.
![15625921729013680445791484534155](https://user-images.githubusercontent.com/51037594/60813559-dd0f5e80-a148-11e9-97c0-5464f4fbc414.jpg)
