### ISSUE TITLE
None of the nodes accept a Name

### ISSUE THREAD

**Issue by bland328** [alisdairjsmyth/node-red-contrib-lifx-api#5]
None of the nodes (I've tested `lifx list lights`, `lifx set state`, `lifx set states`, `lifx toggle power`, `lifx pulse effect`, `lifx breathe effect` and `lifx cycle`) will accept a Name (as assigned from the standard Node Properties panel in the Node-RED GUI).

I've tested both node-red-contrib-lifx-api 1.0.5 and 1.0.6.

No error is evident--the name simply vanishes after the Done button is clicked.

**Comment by alisdairjsmyth** [comment]
Fix available in v1.0.7
